#define _GNU_SOURCE
/*
 * rbox-wrap.c - ReadOnlyBox wrapper for executing read-only commands
 * 
 * This is a thin wrapper that:
 * 1. Checks embedded DFA for fast-path approval
 * 2. Queries the server for a decision on a command
 * 3. If allowed, executes the command locally
 * 4. If denied, prints the denial and exits with error
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <sys/wait.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/prctl.h>
#include <getopt.h>
#include <pwd.h>
#include <sys/un.h>
#ifndef UNIX_PATH_MAX
#define UNIX_PATH_MAX 108
#endif
#include <limits.h>

#include <rbox_protocol.h>
#include <shell_tokenizer.h>
#include <dfa.h>
#include <dfa_types.h>

/* Embedded DFA data (generated by build system) */
extern const unsigned char rbox_wrap_dfa_data[];
extern const size_t rbox_wrap_dfa_data_size;

/* Expected DFA identifier - must match pattern file */
static const char* EXPECTED_IDENTIFIER = "rbox-wrap-cmd-v1";

#ifndef DEFAULT_SOCKET
#define DEFAULT_SOCKET "/run/readonlybox/readonlybox.sock"
#endif

#define ENV_FLAGGED_ENVS "READONLYBOX_FLAGGED_ENVS"
#define ENV_CALLER      "READONLYBOX_CALLER"
#define ENV_UID         "READONLYBOX_UID"

#define EXIT_ALLOW  0
#define EXIT_DENY   9
#define EXIT_ERROR  1

/* Global DFA state */
static const void *g_dfa_data = NULL;
static size_t g_dfa_size = 0;
static int g_dfa_validated = 0;

static const char *program_name = "rbox-wrap";

static void usage(const char *prog) {
    fprintf(stderr, "Usage: %s [options] [--] <command> [args...]\n", prog);
    fprintf(stderr, "   or: %s [options] <command> [args...]\n", prog);
    fprintf(stderr, "\nOptions:\n");
    fprintf(stderr, "  --judge       Query server for decision, print result (default)\n");
    fprintf(stderr, "  --run         Query server and execute if allowed\n");
    fprintf(stderr, "  --clear-env   Run with clean environment (no server env filtering)\n");
    fprintf(stderr, "  --bin         Output raw response packet to stdout\n");
    fprintf(stderr, "  --relay       Skip DFA, always contact server\n");
    fprintf(stderr, "  --socket      Unix socket path (default: %s)\n", DEFAULT_SOCKET);
    fprintf(stderr, "  --uid         Drop privileges to this UID (for privilege separation)\n");
    fprintf(stderr, "  -h, --help    Show this help\n");
    fprintf(stderr, "  --version     Show version information\n");
    fprintf(stderr, "\nEnvironment:\n");
    fprintf(stderr, "  %s  Flagged env vars for server (set by ptrace client)\n", ENV_FLAGGED_ENVS);
    fprintf(stderr, "  %s        Caller info (set by ptrace client)\n", ENV_CALLER);
    fprintf(stderr, "  %s         UID to run as (set by ptrace client)\n", ENV_UID);
    fprintf(stderr, "\nExit codes:\n");
    fprintf(stderr, "  0 - Command allowed and executed (--run only)\n");
    fprintf(stderr, "  1 - Command denied or error\n");
    fprintf(stderr, "  9 - Server decision (deny once) printed\n");
}

static void version_info(void) {
    fprintf(stderr, "%s v1.0.0\n", program_name);
    fprintf(stderr, "ReadOnlyBox wrapper for executing read-only commands\n");
}

/* Initialize embedded DFA */
static int init_embedded_dfa(void) {
    if (g_dfa_validated) {
        return 0;
    }
    
    g_dfa_data = rbox_wrap_dfa_data;
    g_dfa_size = rbox_wrap_dfa_data_size;
    
    /* Validate identifier */
    if (!dfa_eval_validate_id(g_dfa_data, g_dfa_size, EXPECTED_IDENTIFIER)) {
        if (!dfa_eval_validate_id(g_dfa_data, g_dfa_size, "rbox-wrap")) {
            g_dfa_data = NULL;
            g_dfa_size = 0;
            return -1;
        }
    }
    
    g_dfa_validated = 1;
    return 0;
}

/* Build command string from argv - dynamic allocation */
static char *build_command_string_alloc(const char *const *argv) {
    if (!argv || !argv[0]) return NULL;

    size_t total_len = 0;
    for (int i = 0; argv[i]; i++) {
        total_len += strlen(argv[i]) + 1;
    }
    
    if (total_len == 0) return NULL;
    
    char *buf = malloc(total_len + 1);
    if (!buf) return NULL;
    
    char *p = buf;
    for (int i = 0; argv[i]; i++) {
        if (i > 0) {
            *p++ = ' ';
        }
        size_t len = strlen(argv[i]);
        memcpy(p, argv[i], len);
        p += len;
    }
    *p = '\0';
    
    return buf;
}

/* Parse flagged environment variables from READONLYBOX_FLAGGED_ENVS
 * Format: NAME1:score1,NAME2:score2,...
 * Returns count and allocates names and scores arrays (caller must free both) */
static int parse_flagged_envs(const char *env_str, char ***out_names, float **out_scores) {
    if (out_names) *out_names = NULL;
    if (out_scores) *out_scores = NULL;
    
    if (!env_str || !*env_str) {
        return 0;
    }

    int count = 1;
    for (const char *p = env_str; *p; p++) {
        if (*p == ',') count++;
    }

    char **names = calloc(count, sizeof(char *));
    float *scores = calloc(count, sizeof(float));
    if (!names || !scores) {
        free(names);
        free(scores);
        return 0;
    }

    char *env_copy = strdup(env_str);
    if (!env_copy) {
        free(names);
        free(scores);
        return 0;
    }

    int idx = 0;
    char *token = strtok(env_copy, ",");
    while (token && idx < count) {
        char *colon = strchr(token, ':');
        if (colon) {
            *colon = '\0';
            scores[idx] = (float)atof(colon + 1);
        } else {
            scores[idx] = 0.0f;
        }
        names[idx] = strdup(token);
        if (!names[idx]) {
            for (int j = 0; j < idx; j++) {
                free(names[j]);
            }
            free(names);
            free(scores);
            free(env_copy);
            return -1;
        }
        idx++;
        token = strtok(NULL, ",");
    }
    free(env_copy);

    if (out_names) *out_names = names;
    else free(names);
    if (out_scores) *out_scores = scores;
    else free(scores);
    return idx;
}

/* Free flagged environment names */
static void free_flagged_envs(int count, char **names) {
    if (names) {
        for (int i = 0; i < count; i++) {
            free(names[i]);
        }
        free(names);
    }
}

/* Apply environment filtering based on server response
 * Removes environment variables that the server marked as denied */
static void apply_env_filter(int flagged_count, char **flagged_names, 
                            rbox_env_decisions_t *env_decisions) {
    if (!env_decisions || !env_decisions->valid || !env_decisions->bitmap) {
        return;
    }
    
    for (int i = 0; i < flagged_count && i < env_decisions->env_count; i++) {
        if (!flagged_names[i]) continue;
        
        int bit = (env_decisions->bitmap[i / 8] >> (i % 8)) & 1;
        if (bit == 1) {
            unsetenv(flagged_names[i]);
        }
    }
}

/* Check DFA for fast-path approval
 * Returns: 1 if allowed, 0 if not, -1 on error/unavailable */
static int check_dfa(int argc, const char *const *args) {
    (void)argc;
    
    /* Only use embedded DFA */
    if (init_embedded_dfa() != 0) {
        return -1;
    }
    
    if (!g_dfa_data) {
        return -1;
    }
    
    char *cmd_str = build_command_string_alloc(args);
    if (!cmd_str) {
        return -1;
    }
    
    dfa_result_t result;
    bool eval_ok = dfa_eval(g_dfa_data, g_dfa_size, cmd_str, strlen(cmd_str), &result);
    
    free(cmd_str);
    
    if (!eval_ok) {
        return -1;
    }
    
    if (result.matched && (result.category_mask & CAT_MASK_AUTOALLOW)) {
        return 1;
    }
    
    return 0;
}

/* Get target UID from environment or option */
static uid_t get_target_uid(const char *uid_str) {
    const char *env_uid = getenv(ENV_UID);
    const char *src = uid_str ? uid_str : (env_uid ? env_uid : NULL);
    if (!src) return (uid_t)-1;
    
    char *end;
    unsigned long val = strtoul(src, &end, 10);
    if (end == src || *end != '\0' || val > 65534) {
        return (uid_t)-1;
    }
    return (uid_t)val;
}

/* Write all data to file descriptor, handling partial writes */
static int write_all(int fd, const void *data, size_t len) {
    const char *p = data;
    size_t written = 0;
    while (written < len) {
        ssize_t n = write(fd, p + written, len - written);
        if (n < 0) {
            if (errno == EINTR) continue;
            return -1;
        }
        if (n == 0) {
            return -1;
        }
        written += n;
    }
    return 0;
}

/* Execute command with optional privilege dropping and clean env */
static int run_command(const char *cmd, char *argv[], uid_t target_uid, int clear_env) {
    pid_t pid = fork();
    if (pid < 0) {
        fprintf(stderr, "%s: fork: %s\n", program_name, strerror(errno));
        return -1;
    }
    
    if (pid == 0) {
        /* Child process */
        
        /* Request parent death signal */
        prctl(PR_SET_PDEATHSIG, SIGTERM);
        
        /* Determine target user info for environment */
        const char *home = "/root";
        const char *user = "root";
        if (target_uid != (uid_t)-1) {
            struct passwd *pw = getpwuid(target_uid);
            if (pw) {
                home = pw->pw_dir ? pw->pw_dir : "/root";
                user = pw->pw_name ? pw->pw_name : "root";
            }
        }
        
        /* Handle clean environment option */
        if (clear_env) {
            clearenv();
            setenv("PATH", "/usr/local/bin:/usr/bin:/bin", 1);
            setenv("HOME", home, 1);
            setenv("USER", user, 1);
        }
        
        /* Drop privileges if requested */
        if (target_uid != (uid_t)-1) {
            struct passwd *pw = getpwuid(target_uid);
            if (pw) {
                if (setgid(pw->pw_gid) != 0 || setuid(pw->pw_uid) != 0) {
                    fprintf(stderr, "%s: failed to drop privileges: %s\n", 
                            program_name, strerror(errno));
                    _exit(1);
                }
            }
        }
        
        /* Execute command */
        execvp(cmd, argv);
        fprintf(stderr, "%s: %s: %s\n", program_name, cmd, strerror(errno));
        _exit(127);
    }
    
    /* Parent: wait for child */
    int status;
    while (waitpid(pid, &status, 0) < 0) {
        if (errno != EINTR) {
            return -1;
        }
    }
    
    if (WIFEXITED(status)) {
        return WEXITSTATUS(status);
    }
    if (WIFSIGNALED(status)) {
        return 128 + WTERMSIG(status);
    }
    return -1;
}

/* Handle --run mode with environment filtering
 * Uses binary protocol to get env decisions from server */
static int run_with_filter(const char *socket_path, const char *command, 
                          int cmd_argc, const char **args,
                          const char *caller, const char *syscall,
                          int flagged_count, char **flagged_names, float *flagged_scores,
                          uid_t target_uid, int clear_env) {
    char *packet = NULL;
    size_t pkt_len = 0;
    
    rbox_error_t err = rbox_blocking_request_raw(
        socket_path,
        command,
        cmd_argc,
        args,
        caller,
        syscall,
        flagged_count,
        (const char **)flagged_names,
        flagged_scores,
        &packet,
        &pkt_len,
        100,
        3
    );
    
    if (err != RBOX_OK || !packet) {
        fprintf(stderr, "%s: server request failed: %s\n", 
                program_name, rbox_strerror(err));
        return EXIT_ERROR;
    }
    
    /* Decode the response */
    rbox_decoded_header_t header;
    rbox_decode_header(packet, pkt_len, &header);
    
    if (!header.valid) {
        fprintf(stderr, "%s: invalid response header\n", program_name);
        free(packet);
        return EXIT_ERROR;
    }
    
    rbox_response_details_t details;
    rbox_decode_response_details(&header, packet, pkt_len, &details);
    
    rbox_env_decisions_t env_decisions;
    rbox_decode_env_decisions(&header, &details, packet, pkt_len, &env_decisions);
    
    /* Apply environment filtering unless clear_env is set */
    if (!clear_env && env_decisions.valid) {
        apply_env_filter(flagged_count, flagged_names, &env_decisions);
    }
    
    /* Free decoded data */
    rbox_free_env_decisions(&env_decisions);
    
    /* Check decision */
    if (!details.valid || details.decision != RBOX_DECISION_ALLOW) {
        if (details.valid && details.decision == RBOX_DECISION_DENY) {
            printf("DENY %s\n", details.reason[0] ? details.reason : "");
            free(packet);
            return EXIT_DENY;
        }
        fprintf(stderr, "%s: invalid server response\n", program_name);
        free(packet);
        return EXIT_ERROR;
    }
    
    /* Execute the command */
    int result = run_command(command, (char **)args, target_uid, clear_env);
    free(packet);
    return result;
}

int main(int argc, char *argv[]) {
    const char *socket_path = DEFAULT_SOCKET;
    int mode_run = 0;
    int mode_bin = 0;
    int mode_relay = 0;
    int mode_clear_env = 0;
    const char *uid_str = NULL;
    
    program_name = argv[0];
    
    static struct option long_options[] = {
        {"judge",    no_argument,       0, 'j'},
        {"run",      no_argument,       0, 'r'},
        {"clear-env",no_argument,       0, 'c'},
        {"bin",      no_argument,       0, 'b'},
        {"relay",    no_argument,       0, 'l'},
        {"socket",   required_argument, 0, 's'},
        {"uid",      required_argument, 0, 'u'},
        {"help",     no_argument,       0, 'h'},
        {"version",  no_argument,       0, 'v'},
        {0, 0, 0, 0}
    };
    
    int opt;
    int option_index = 0;
    while ((opt = getopt_long(argc, argv, "s:u:hrbclv", 
                              long_options, &option_index)) != -1) {
        switch (opt) {
            case 'h':
                usage(argv[0]);
                return 0;
            case 'v':
                version_info();
                return 0;
            case 's':
                socket_path = optarg;
                if (strlen(socket_path) >= UNIX_PATH_MAX) {
                    fprintf(stderr, "%s: socket path too long (max %d)\n",
                            program_name, UNIX_PATH_MAX);
                    return EXIT_ERROR;
                }
                break;
            case 'u':
                uid_str = optarg;
                break;
            case 'j':
                mode_run = 0;
                break;
            case 'r':
                mode_run = 1;
                break;
            case 'c':
                mode_clear_env = 1;
                break;
            case 'b':
                mode_bin = 1;
                break;
            case 'l':
                mode_relay = 1;
                break;
            default:
                usage(argv[0]);
                return 1;
        }
    }
    
    /* Check for -- separator */
    int cmd_start = optind;
    for (int i = optind; i < argc; i++) {
        if (strcmp(argv[i], "--") == 0) {
            cmd_start = i + 1;
            break;
        }
    }
    
    if (cmd_start >= argc) {
        fprintf(stderr, "Error: No command specified\n");
        usage(argv[0]);
        return EXIT_ERROR;
    }
    
    const char *command = argv[cmd_start];
    int cmd_argc = argc - cmd_start;
    char **cmd_argv = &argv[cmd_start];
    const char **args = (const char **)cmd_argv;
    
    uid_t target_uid = get_target_uid(uid_str);
    
    /* Initialize protocol library */
    rbox_init();
    
    /* Determine caller from environment or mode */
    const char *caller_env = getenv(ENV_CALLER);
    const char *caller = caller_env ? caller_env : (mode_run ? "run" : "judge");
    const char *syscall = "execve";
    
    /* Check DFA first for fast-path (unless --relay) */
    int dfa_result = -1;
    if (!mode_relay) {
        dfa_result = check_dfa(cmd_argc, args);
    }
    
    /* Handle DFA fast-path */
    if (dfa_result == 1) {
        if (mode_bin) {
            char *packet = NULL;
            size_t pkt_len = 0;
            rbox_error_t build_err = rbox_build_response(
                RBOX_DECISION_ALLOW, "DFA fast-path", 0, 0, 0, NULL, &packet, &pkt_len);
            if (build_err != RBOX_OK || !packet) {
                fprintf(stderr, "%s: failed to build response packet\n", program_name);
                return EXIT_ERROR;
            }
            if (write_all(STDOUT_FILENO, packet, pkt_len) != 0) {
                fprintf(stderr, "%s: failed to write packet\n", program_name);
                free(packet);
                return EXIT_ERROR;
            }
            free(packet);
            return EXIT_ALLOW;
        } else {
            printf("ALLOW DFA fast-path\n");
            if (mode_run) {
                int ret = run_command(command, cmd_argv, target_uid, mode_clear_env);
                return ret < 0 ? EXIT_ERROR : ret;
            }
            return EXIT_ALLOW;
        }
    }
    
    /* Parse flagged environment variables */
    char **flagged_names = NULL;
    float *flagged_scores = NULL;
    int flagged_count = 0;
    if (!mode_clear_env) {
        const char *env_str = getenv(ENV_FLAGGED_ENVS);
        flagged_count = parse_flagged_envs(env_str, &flagged_names, &flagged_scores);
        if (flagged_count < 0) {
            fprintf(stderr, "%s: failed to parse flagged envs\n", program_name);
            return EXIT_ERROR;
        }
    }
    
    /* Handle --run mode with environment filtering */
    if (mode_run) {
        int ret = run_with_filter(socket_path, command, cmd_argc, args,
                             caller, syscall, flagged_count, flagged_names, flagged_scores,
                             target_uid, mode_clear_env);
        free_flagged_envs(flagged_count, flagged_names);
        free(flagged_scores);
        return ret;
    }
    
    /* Handle --bin mode (binary protocol, no execution) */
    if (mode_bin) {
        char *packet = NULL;
        size_t pkt_len = 0;
        rbox_error_t err = rbox_blocking_request_raw(
            socket_path,
            command,
            cmd_argc,
            args,
            caller,
            syscall,
            flagged_count,
            (const char **)flagged_names,
            flagged_scores,
            &packet,
            &pkt_len,
            100,
            3
        );
        
        free_flagged_envs(flagged_count, flagged_names);
        free(flagged_scores);
        
        if (err != RBOX_OK || !packet) {
            fprintf(stderr, "%s: %s\n", program_name, rbox_strerror(err));
            return EXIT_ERROR;
        }
        
        if (write_all(STDOUT_FILENO, packet, pkt_len) != 0) {
            fprintf(stderr, "%s: failed to write packet\n", program_name);
            free(packet);
            return EXIT_ERROR;
        }
        free(packet);
        return EXIT_ALLOW;
    }
    
    /* Default: text mode query to server (judge mode) */
    rbox_response_t response;
    rbox_error_t err = rbox_blocking_request(
        socket_path,
        command,
        cmd_argc,
        args,
        caller,
        syscall,
        flagged_count,
        (const char **)flagged_names,
        flagged_scores,
        &response,
        100,
        3
    );
    
    free_flagged_envs(flagged_count, flagged_names);
    free(flagged_scores);
    
    if (err != RBOX_OK) {
        fprintf(stderr, "%s: %s\n", program_name, rbox_strerror(err));
        return EXIT_ERROR;
    }
    
    if (response.decision == RBOX_DECISION_ALLOW) {
        printf("ALLOW %s\n", response.reason[0] ? response.reason : "");
        return EXIT_ALLOW;
    }
    else if (response.decision == RBOX_DECISION_DENY) {
        printf("DENY %s\n", response.reason[0] ? response.reason : "");
        return EXIT_DENY;
    }
    else {
        fprintf(stderr, "%s: Unknown decision: %d\n", program_name, response.decision);
        return EXIT_ERROR;
    }
}
