#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <ctype.h>
#include "../include/dfa_types.h"

/**
 * Advanced NFA to DFA Converter
 *
 * This tool reads NFA files generated by the advanced nfa_builder
 * and converts them to compact DFA binary format.
 */

#define MAX_STATES 4096
#define MAX_CHARS 256
#define MAX_LINE_LENGTH 2048

// Build-time DFA State
typedef struct {
    uint32_t transitions_offset;  // Offset to transition table (runtime format)
    uint16_t transition_count;    // Number of transitions
    uint16_t flags;               // State flags (accepting, error, etc.)
    bool accepting;               // Build-time accepting flag
    int transitions[MAX_CHARS];   // -1 = no transition, otherwise state index
    int nfa_states[MAX_STATES];   // Set of NFA states
    int nfa_state_count;
} build_dfa_state_t;

// NFA State for reading NFA files
typedef struct {
    bool accepting;
    char* tags[MAX_STATES];
    int tag_count;
    int transitions[MAX_CHARS]; // -1 = no transition, otherwise state index
    int transition_count;
} nfa_state_t;

// Global variables
static nfa_state_t nfa[MAX_STATES];
static build_dfa_state_t dfa[MAX_STATES];
static int nfa_state_count = 0;
static int dfa_state_count = 0;

// Initialize NFA
void nfa_init(void) {
    for (int i = 0; i < MAX_STATES; i++) {
        nfa[i].accepting = false;
        nfa[i].tag_count = 0;
        for (int j = 0; j < MAX_STATES; j++) {
            nfa[i].tags[j] = NULL;
        }
        for (int j = 0; j < MAX_CHARS; j++) {
            nfa[i].transitions[j] = -1;
        }
        nfa[i].transition_count = 0;
    }
    nfa_state_count = 0;
}

// Initialize DFA
void dfa_init(void) {
    for (int i = 0; i < MAX_STATES; i++) {
        dfa[i].accepting = false;
        dfa[i].flags = 0;
        dfa[i].transition_count = 0;
        dfa[i].nfa_state_count = 0;
        for (int j = 0; j < MAX_CHARS; j++) {
            dfa[i].transitions[j] = -1;
        }
        for (int j = 0; j < MAX_STATES; j++) {
            dfa[i].nfa_states[j] = -1;
        }
    }
    dfa_state_count = 0;
}

// Add DFA state
int dfa_add_state(bool accepting, int* nfa_states, int nfa_count) {
    if (dfa_state_count >= MAX_STATES) {
        fprintf(stderr, "Error: Maximum DFA states reached\n");
        exit(1);
    }

    int state = dfa_state_count;
    dfa[state].accepting = accepting;
    dfa[state].flags = accepting ? DFA_STATE_ACCEPTING : 0;
    dfa[state].transition_count = 0;
    dfa[state].nfa_state_count = 0;

    // Copy NFA states
    for (int i = 0; i < nfa_count && i < MAX_STATES; i++) {
        dfa[state].nfa_states[i] = nfa_states[i];
        dfa[state].nfa_state_count++;
    }

    dfa_state_count++;
    return state;
}

// Compute epsilon closure for NFA states
void epsilon_closure(int* states, int* count, int max_states) {
    // Simple implementation - in a real system, this would be more sophisticated
    // For now, we'll just use the states as-is
}

// Move NFA states on character
void nfa_move(int* states, int* count, char c, int max_states) {
    int new_states[MAX_STATES];
    int new_count = 0;

    for (int i = 0; i < *count; i++) {
        int state = states[i];
        if (state < 0 || state >= nfa_state_count) continue;

        // Check direct transition
        if (nfa[state].transitions[c] != -1) {
            int target = nfa[state].transitions[c];

            // Check if already in new_states
            bool found = false;
            for (int j = 0; j < new_count; j++) {
                if (new_states[j] == target) {
                    found = true;
                    break;
                }
            }

            if (!found && new_count < max_states) {
                new_states[new_count] = target;
                new_count++;
            }
        }

        // Check wildcard transition (ANY)
        if (nfa[state].transitions[DFA_CHAR_ANY] != -1) {
            int target = nfa[state].transitions[DFA_CHAR_ANY];

            // Check if already in new_states
            bool found = false;
            for (int j = 0; j < new_count; j++) {
                if (new_states[j] == target) {
                    found = true;
                    break;
                }
            }

            if (!found && new_count < max_states) {
                new_states[new_count] = target;
                new_count++;
            }
        }
    }

    // Copy back
    for (int i = 0; i < new_count && i < max_states; i++) {
        states[i] = new_states[i];
    }
    *count = new_count;
}

// Convert NFA to DFA using subset construction
void nfa_to_dfa(void) {
    dfa_init();

    // Initial DFA state: epsilon closure of NFA initial state
    int initial_nfa_states[MAX_STATES];
    initial_nfa_states[0] = 0;
    int initial_count = 1;

    epsilon_closure(initial_nfa_states, &initial_count, MAX_STATES);

    // Check if any NFA state is accepting
    bool accepting = false;
    for (int i = 0; i < initial_count; i++) {
        if (nfa[initial_nfa_states[i]].accepting) {
            accepting = true;
            break;
        }
    }

    // Add initial DFA state
    int initial_dfa = dfa_add_state(accepting, initial_nfa_states, initial_count);

    // Queue for unprocessed DFA states
    int queue[MAX_STATES];
    int queue_start = 0;
    int queue_end = 1;
    queue[0] = initial_dfa;

    // Process queue
    while (queue_start < queue_end) {
        int current_dfa = queue[queue_start];
        queue_start++;

        // Try each possible input character (only printable ASCII for now)
        for (char c = 32; c < 127; c++) {
            // Compute move on character c
            int moved_states[MAX_STATES];
            int moved_count = dfa[current_dfa].nfa_state_count;

            for (int i = 0; i < moved_count; i++) {
                moved_states[i] = dfa[current_dfa].nfa_states[i];
            }

            nfa_move(moved_states, &moved_count, c, MAX_STATES);
            epsilon_closure(moved_states, &moved_count, MAX_STATES);

            if (moved_count == 0) {
                // No transition
                continue;
            }

            // Check if this set of NFA states already exists in DFA
            int existing_dfa = -1;
            for (int i = 0; i < dfa_state_count; i++) {
                if (dfa[i].nfa_state_count != moved_count) {
                    continue;
                }

                bool match = true;
                for (int j = 0; j < moved_count; j++) {
                    bool found = false;
                    for (int k = 0; k < dfa[i].nfa_state_count; k++) {
                        if (dfa[i].nfa_states[k] == moved_states[j]) {
                            found = true;
                            break;
                        }
                    }
                    if (!found) {
                        match = false;
                        break;
                    }
                }

                if (match) {
                    existing_dfa = i;
                    break;
                }
            }

            if (existing_dfa != -1) {
                // Reuse existing DFA state
                dfa[current_dfa].transitions[c] = existing_dfa;
                dfa[current_dfa].transition_count++;
            } else {
                // Create new DFA state
                bool new_accepting = false;
                for (int i = 0; i < moved_count; i++) {
                    if (nfa[moved_states[i]].accepting) {
                        new_accepting = true;
                        break;
                    }
                }

                int new_dfa = dfa_add_state(new_accepting, moved_states, moved_count);
                dfa[current_dfa].transitions[c] = new_dfa;
                dfa[current_dfa].transition_count++;

                // Add to queue
                if (queue_end < MAX_STATES) {
                    queue[queue_end] = new_dfa;
                    queue_end++;
                }
            }
        }
    }
}

// Read NFA file (advanced format)
void read_nfa_file(const char* filename) {
    FILE* file = fopen(filename, "r");
    if (file == NULL) {
        fprintf(stderr, "Error: Cannot open file %s\n", filename);
        exit(1);
    }

    char line[MAX_LINE_LENGTH];
    int current_state = -1;
    int max_state_id = -1;

    nfa_init();

    while (fgets(line, sizeof(line), file)) {
        // Remove newline and carriage return
        size_t len = strlen(line);
        while (len > 0 && (line[len-1] == '\n' || line[len-1] == '\r')) {
            line[len-1] = '\0';
            len--;
        }

        // Skip empty lines
        if (len == 0) {
            continue;
        }

        // Parse NFA file format
        if (strncmp(line, "States:", 7) == 0) {
            // States count line
            sscanf(line, "States: %d", &nfa_state_count);
        } else if (strncmp(line, "State ", 6) == 0) {
            // State definition
            int state_id;
            if (sscanf(line, "State %d:", &state_id) == 1) {
                current_state = state_id;
                if (state_id > max_state_id) {
                    max_state_id = state_id;
                }
            }
        } else if (current_state >= 0 && strncmp(line, "  Accepting:", 12) == 0) {
            // Accepting state
            char accepting_str[16];
            sscanf(line, "  Accepting: %s", accepting_str);
            nfa[current_state].accepting = strcmp(accepting_str, "yes") == 0;
        } else if (current_state >= 0 && strncmp(line, "    '", 5) == 0) {
            // Character transition
            char char_str[10];
            int target_state;
            if (sscanf(line, "    '%[^']' -> %d", char_str, &target_state) == 2) {
                char c = char_str[0];
                nfa[current_state].transitions[(unsigned char)c] = target_state;
                nfa[current_state].transition_count++;
            }
        } else if (current_state >= 0 && strncmp(line, "    ANY", 7) == 0) {
            // Wildcard transition
            int target_state;
            if (sscanf(line, "    ANY -> %d", &target_state) == 1) {
                nfa[current_state].transitions[DFA_CHAR_ANY] = target_state;
                nfa[current_state].transition_count++;
            }
        } else if (current_state >= 0 && strncmp(line, "    0x", 6) == 0) {
            // Hex character transition
            unsigned int char_val;
            int target_state;
            if (sscanf(line, "    0x%X -> %d", &char_val, &target_state) == 2) {
                unsigned char c = (unsigned char)char_val;
                nfa[current_state].transitions[c] = target_state;
                nfa[current_state].transition_count++;
            }
        }
    }

    fclose(file);

    // Set actual state count based on max state ID found
    if (max_state_id >= 0) {
        nfa_state_count = max_state_id + 1;
    }

    printf("Read NFA with %d states from %s\n", nfa_state_count, filename);
}

// Write DFA to binary file
void write_dfa_binary(const char* filename) {
    FILE* file = fopen(filename, "wb");
    if (file == NULL) {
        fprintf(stderr, "Error: Cannot create file %s\n", filename);
        exit(1);
    }

    // DFA header
    struct {
        uint32_t magic;
        uint16_t version;
        uint16_t state_count;
        uint32_t initial_state;
        uint32_t accepting_mask;
    } header;

    header.magic = DFA_MAGIC;
    header.version = DFA_VERSION;
    header.state_count = dfa_state_count;
    header.initial_state = sizeof(header);
    header.accepting_mask = 0;

    // Write header
    fwrite(&header, sizeof(header), 1, file);

    // Calculate state offsets
    size_t current_offset = sizeof(header);

    // Write states (placeholder for now - we'll write transitions after)
    for (int i = 0; i < dfa_state_count; i++) {
        build_dfa_state_t state = dfa[i];
        state.transitions_offset = current_offset;

        // Write transitions
        for (int c = 0; c < MAX_CHARS; c++) {
            if (state.transitions[c] != -1) {
                dfa_transition_t trans = {
                    .character = c,
                    .next_state_offset = sizeof(header) + (state.transitions[c] * sizeof(build_dfa_state_t))
                };
                fwrite(&trans, sizeof(trans), 1, file);
                current_offset += sizeof(trans);
            }
        }

        // Write end marker
        dfa_transition_t end_marker = {.character = 0, .next_state_offset = 0};
        fwrite(&end_marker, sizeof(end_marker), 1, file);
        current_offset += sizeof(end_marker);

        // Update transition count
        state.transition_count = 0;
        for (int c = 0; c < MAX_CHARS; c++) {
            if (state.transitions[c] != -1) {
                state.transition_count++;
            }
        }

        // Write state
        fwrite(&state, sizeof(state), 1, file);
    }

    fclose(file);
    printf("Wrote DFA with %d states to %s\n", dfa_state_count, filename);
}

// Main function
int main(int argc, char* argv[]) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <nfa_file> [output.dfa]\n", argv[0]);
        fprintf(stderr, "\n");
        fprintf(stderr, "Advanced NFA to DFA Converter\n");
        fprintf(stderr, "Reads NFA files from advanced nfa_builder and converts to DFA binary\n");
        fprintf(stderr, "\n");
        fprintf(stderr, "Example:\n");
        fprintf(stderr, "  %s minimal.nfa readonlybox.dfa\n", argv[0]);
        return 1;
    }

    const char* nfa_file = argv[1];
    const char* output_file = argc > 2 ? argv[2] : "readonlybox.dfa";

    printf("Advanced NFA to DFA Converter\n");
    printf("==============================\n\n");

    // Read NFA file
    read_nfa_file(nfa_file);

    // Convert NFA to DFA
    printf("Converting NFA to DFA...\n");
    nfa_to_dfa();
    printf("Created DFA with %d states\n\n", dfa_state_count);

    // Write DFA binary
    printf("Writing DFA binary...\n");
    write_dfa_binary(output_file);

    printf("\nDone!\n");
    return 0;
}